### ISSUE TITLE
changing `log.debug` has no effect

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-client-log#1]
```
> var Log = require('hoodie-client-log')
> var log = new Log('hoodie')
> log('yo')
(hoodie:log) yo
> log.info('yo')
undefined
> log.warn('yo')
(hoodie:warn) yo
> log.level = 'debug'
'debug'
> log.info('yo')
undefined
```

The last `log.info` call should log to output, but doesn't. 

It would be nice to add an integration test for this, but no idea how to test for correct log output. Maybe there is something that lets us mock `console`

---
- [x] claim this issue (comment below)
- [x] start a pull request
- [x] write tests
- [x] implement
- [x] update README
- [ ] review & merge

Comment bellow, ping me in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/gr2m/) if you have any questions

**Comment by willmanduffy** [comment]
Did a little dive onto this tonight to research. From what I found there's no real setter on `level` (or `prefix` which is related to #15). By removing

``` js
api.level = state.level
```

from `index.js` and replacing it with something along the lines of:

``` js
Object.defineProperty(api, 'level', {
  get: function () { return state.level },
  set: function (newValue) { state.level = newValue }
})
```

You'll end up with the proper functionality: 

``` js
> log.level
'warn'
> log.debug('yo')
undefined
> log.level = 'debug'
'debug'
> log.debug('yo')
(hoodie:debug) yo
```

The one tradeoff I have observed from this so far is that it seems to remove `level` from `log.scoped()`. If you add `enumerable: true` to the `defineProperty` but won't show the actual value anymore.

Hope this helps!

**Comment by gr2m** [comment]
I've started a PR to fix it here: https://github.com/hoodiehq/hoodie-client-log/pull/18
Does it look good from your side @philduffy? I couldn't reproduce an issue with `level` and `log.scoped()`, could you double check if I’ve overseen something?

**Comment by willmanduffy** [comment]
Yup that PR LGTM @gr2m. My only comment is that `level` no longer shows up in enumeration of the Log object. 

Before:

``` js
➜  hoodie-client-log git:(master) node
> var Log = require('./'); var log = new Log('hoodie');
undefined
> log
{ [Function: bound log]
  debug: [Function: bound debug],
  info: [Function: bound info],
  warn: [Function: bound warn],
  error: [Function: bound error],
  scoped: [Function],
  prefix: 'hoodie',
  level: 'warn' }
```

Your branch:

``` js
➜  hoodie-client-log git:(1-level) ✗ node
> var Log = require('./'); var log = new Log('hoodie');
undefined
> log
{ [Function: bound log]
  debug: [Function: bound debug],
  info: [Function: bound info],
  warn: [Function: bound warn],
  error: [Function: bound error],
  scoped: [Function],
  prefix: 'hoodie' }
```

You can change that by using `enumerable: true` in the `defineProperty` but I'm not sure how much that matters. It also no longer nicely prints 'warn' like it did before it'll show something like `[setter/getter]` but it's still nice to know the property exists.

**Comment by gr2m** [comment]
oh right totally forgot about `enumerable: true`, I'll put that in, why not, thanks for the review @philduffy
