### ISSUE TITLE
Prevent invalid values for level

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-client-log#16]
Throw an error if a user sets `level` to something else but `debug`, `info`, `warn` or `error`, by using a getter/setter pair

``` js
log.level = 'foo'
// throws InvalidValue error
```

---
- [ ] claim this issue (comment below)
- [ ] start a pull request
- [ ] write tests
- [ ] implement
- [ ] update README
- [ ] review & merge

Comment bellow, ping me in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/gr2m/) if you have any questions

**Comment by ianstalter123** [comment]
I should be able to do this one (if its ok to use an if statement to check for log level) like : 

```
 Object.defineProperty(api, 'level', {
    get: function () {
      return state.level
    },
    set: function (newValue) {
      if (['debug', 'error', 'info', 'warn'].indexOf(newValue) > -1) {
        state.level = newValue
      } 
```

**Comment by gr2m** [comment]
done via https://github.com/hoodiehq/hoodie-client-log/pull/19

**Comment by gr2m** [comment]
released as https://github.com/hoodiehq/hoodie-client-log/releases/tag/v1.0.2
