### ISSUE TITLE
migrate to new architecture

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-client-log#31]
part of https://github.com/hoodiehq/hoodie/issues/458

I tried to think of all the steps to migrate this module to the new architecture:
- [x] rename GitHub repository to `hoodie-log`
- [x] move `index.js` to `client/index.js`. I would say we can leave the `lib/` and `test/` folder as they are, as this module only has  client code?
- [x] add `"browser": "client/index.js"` to the package.json just for convenience, so we can continue to do `require('hoodie-log')`, won’t harm
- [x] rename the `"name"` in `package.json` to `"@hoodie/log"`
- [x] find  `"github.com/hoodiehq/hoodie-client-log"` and replace with `"github.com/hoodiehq/hoodie-log"` in `package.json`
- [x] find  `"github.com/hoodiehq/hoodie-client-log"` and replace with `"github.com/hoodiehq/hoodie-log"` in `README.md`
- [x] commit changes with `chore: ...` and `docs: ...` commits. At the end add an empty commit:
- [x] add `"publishConfig": {"access": "public"}` to `package.json` (https://docs.npmjs.com/files/package.json#publishconfig, "Scoped packages default to restricted" https://docs.npmjs.com/cli/access#details)

```
chore: renamed module to @hoodie/client-log

BREAKING CHANGE:
The repository has been renamed from `hoodie-client-log` to `@hoodie/client-log` as part of https://github.com/hoodiehq/hoodie/issues/458
```
- [x] start a PR for review #32

Once merged
- [x] deprecate `hoodie-client-log` in the npm registry
- [x] enable coveralls for new repo name (run `COVERALLS_REPO_TOKEN=... npm run test:coverage & npm run test:coverage:upload`, then on coveralls.io require `100%` coverage for success)
- [x] update branch protection: re-enable coveralls 

Once released
- [x] update [hoodie-client package.json](https://github.com/hoodiehq/hoodie-client/blob/65ccb7c346979f76831e7696336179bd67d326c1/package.json#L11)
- [x] update [hoodie-client README.md](https://github.com/hoodiehq/hoodie-client/blob/65ccb7c346979f76831e7696336179bd67d326c1/README.md#hoodielog)
- [x] update [hoodie-client/lib/get-api.js](https://github.com/hoodiehq/hoodie-client/blob/master/lib/get-api.js#L8)

**Comment by gr2m** [comment]
ping @hoodiehq/maintainers could you review to see if I missed anything?
@boennemann will renaming the npm package name "just work" with semantic release"? Or do we need to do an initial release to the npm registry first? Will it continue with the version numbers or try to create 1.0.0 again? That’ll break git tags / releases on GitHub.

**Comment by finnp** [comment]
I am going to start working on the PR.

**Comment by boennemann** [comment]
For a new name semantic-release will start over at 1.0.0. I'd suggest to checkout the last release that happened with the old name. Change name field to the new one. Manually add last released version number to version field. Run `npm publish` once locally.

Important: Don't create a commit, publish with the old commit hash, even if the stage is dirty.

(Given that the configured semantic-release user has access to publish to the new package) semantic-release will pick up the old version number an continue from there.

**Comment by gr2m** [comment]
okay thanks I’ll take care of it
