### ISSUE TITLE
Add an option to disable logging for production environments

### ISSUE THREAD

**Issue by elisechant** [hoodiehq/hoodie-client-log#40]

**Comment by gr2m** [comment]
you can set `log.level` to `'error'`, you wouldn’t usually want to disable error logs in production because they shouldn’t happen in the first place. And if they do you’ll appreciate additional info from the error log message

**Comment by elisechant** [comment]
Thanks @gr2m. Seems legit. Would you like me to document that in a PR?

**Comment by gr2m** [comment]
sure :) Thanks!
